# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_server_latest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_status_id',
            field=models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(db_index=True, max_length=128, verbose_name='SN号'),
        ),
    ]
